# Generated by Django 5.0.6 on 2024-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanFeatureDetails',
            fields=[
                ('subscription_plan_feature_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_plan_id', models.IntegerField(blank=True, null=True)),
                ('subscription_plan_feature_id', models.IntegerField(blank=True, null=True)),
                ('numeric_value', models.IntegerField(blank=True, db_column='Numeric_value', null=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_on', null=True)),
                ('delete_ind', models.CharField(blank=True, db_column='Delete_ind', max_length=5, null=True)),
            ],
            options={
                'db_table': 'subscription_plan_feature_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanSubFeatureDetails',
            fields=[
                ('subscription_plan_sub_feature_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_plan_id', models.IntegerField(blank=True, null=True)),
                ('subscription_plan_sub_feature_id', models.IntegerField(blank=True, null=True)),
                ('numeric_value', models.IntegerField(blank=True, db_column='Numeric_value', null=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_on', null=True)),
                ('delete_ind', models.CharField(blank=True, db_column='Delete_ind', max_length=5, null=True)),
            ],
            options={
                'db_table': 'subscription_plan_sub_feature_details',
                'managed': False,
            },
        ),
    ]
