# Generated by Django 5.0.6 on 2024-07-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscriptionplanfeaturedetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
    ]
