# Generated by Django 5.0.6 on 2024-07-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
