# Generated by Django 5.0.6 on 2024-07-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_authuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthPermission',
        ),
    ]
