# Generated by Django 5.0.3 on 2024-08-05 15:53

import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('given_name', models.CharField(max_length=100, null=True)),
                ('family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to=None)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('email_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('firstname', models.CharField(default=True, max_length=255)),
                ('lastname', models.CharField(default=True, max_length=255)),
                ('mobile_number', models.CharField(default=True, max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.BigIntegerField(default=0)),
                ('delete_ind', models.IntegerField(default=0)),
                ('user_type_id', models.IntegerField(default=0, null=True, verbose_name=home.models.UserType)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
