# Generated by Django 5.0.3 on 2024-08-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signin',
        ),
    ]
